language: c

os:
  - osx
  - linux

compiler:
  - clang
  - gcc


matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  exclude:
  # osx use always clang for build...
  - os: osx
    compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"

install: 
#macos 
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
#linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update || true; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install build-essential; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libpcap-dev libtool autoconf automake autogen; fi 

before_script:
  - ./autogen.sh
#  - lcov --directory . --zerocounters

script:
  - ./configure
  - make
#
#after_script:
  - cd tests
  - ./do.sh

#after_success:
#- cd ${TRAVIS_BUILD_DIR}
#- lcov --directory . --capture --output-file coverage.info # capture coverage info
#- lcov --remove coverage.info 'tests/*' 'packages/*' 'm4/*' 'doc/*' --output-file coverage.info
#- lcov --list coverage.info # debug before upload
#- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls

notifications:
  email:
    recipients:
      - packager@ntop.org
    on_success: never
    on_failure: always
